# Generated by Django 6.1.1 on 2026-09-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(choices=[('Cancha VIP / Pista Premium', 'Cancha VIP / Pista Premium'), ('Cancha General / Pista General', 'Cancha General / Pista General'), ('Campo / Pista', 'Campo / Pista'), ('Platea Baja / Primer Piso', 'Platea Baja / Primer Piso'), ('Platea Alta / Segundo Piso', 'Platea Alta / Segundo Piso'), ('Tribuna / General', 'Tribuna / General'), ('Galería', 'Galería'), ('Suite / VIP', 'Suite / VIP'), ('Zona Platinum', 'Zona Platinum')], max_length=150),
        ),
    ]
