# Generated by Django 6.1.1 on 2026-09-29 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sector_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionDescartada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_descartadas', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_descartadas', to='core.sector')),
            ],
            options={
                'unique_together': {('organizador', 'sector')},
            },
        ),
    ]
