# Generated by Django 6.1.1 on 2026-09-29 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificaciondescartada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leidas', to='core.sector')),
            ],
            options={
                'unique_together': {('organizador', 'sector')},
            },
        ),
    ]
